import mysql.connector
my_db=mysql.connector.connect(host='localhost',user='root',password='Yaswanth12.',database='inventory_control_management')
cur=my_db.cursor()
t='CREATE TABLE PURCHASE(PURCHASE_ID INT PRIMARY KEY NOT NULL,STORE_MODE VARCHAR(40) NOT NULL,PRODUCT_NAME VARCHAR(20) NOT NULL,COLOR VARCHAR(10) NOT NULL,NUMBER_ITEMS INT NOT NULL,PURCHASE_DATE DATE NOT NULL,PURCHASE_AMOUNT FLOAT NOT NULL)'
cur.execute(t)
print("purchase Table Inserted")
t1='CREATE TABLE MANUFACTURE(MANUFACTURE_ID INT NOT NULL,MANUFACTURE_COMPANY VARCHAR(20),DEFECTIVE BIT NOT NULL,NUMBER_ITEMS INT NOT NULL,MANUFACTURE_DATE DATE PRIMARY KEY NOT NULL,PRODUCT_NAME VARCHAR(20) NOT NULL,COLOR VARCHAR(10) NOT NULL)'
cur.execute(t1)
print("Manufacture table created")
t2='CREATE TABLE GOODS(GOODS_ID INT NOT NULL, NUMBER_ITEMS INT NOT NULL, MANUFACTURE_DATE DATE NOT NULL, PRODUCT_NAME VARCHAR(20) NOT NULL,COLOR VARCHAR(20) NOT NULL, PRIMARY KEY(PRODUCT_NAME, COLOR), FOREIGN KEY(MANUFACTURE_DATE) REFERENCES MANUFACTURE(MANUFACTURE_DATE) ON DELETE CASCADE)'
cur.execute(t2)
print("Goods Table created")
t3='CREATE TABLE SALE(SALE_ID INT PRIMARY KEY NOT NULL,STORE_NAME VARCHAR(40) NOT NULL,SALE_DATE DATE NOT NULL,COLOR VARCHAR(10) NOT NULL,NUMBER_ITEMS INT NOT NULL,PRODUCT_NAME VARCHAR(20) NOT NULL,SALE_AMOUNT FLOAT NOT NULL,PROFIT_MARGIN FLOAT,FOREIGN KEY(PRODUCT_NAME, COLOR) REFERENCES GOODS(PRODUCT_NAME, COLOR) ON DELETE CASCADE)'
cur.execute(t3)
print("sale table created")
